# Generated by Django 4.2.7 on 2024-01-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_name_alter_members_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
