# Generated by Django 4.2.7 on 2024-01-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_members_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
