# Generated by Django 4.2.7 on 2024-01-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_word_2_word_3_word_4_word_5_word_6_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word_1',
            new_name='word',
        ),
    ]
