# Generated by Django 4.2.7 on 2024-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_word_1_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='word_2',
        ),
        migrations.DeleteModel(
            name='word_3',
        ),
        migrations.DeleteModel(
            name='word_4',
        ),
        migrations.DeleteModel(
            name='word_5',
        ),
        migrations.DeleteModel(
            name='word_6',
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
