# Generated by Django 4.2.7 on 2024-02-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_delete_word_2_delete_word_3_delete_word_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
