# Generated by Django 4.2.7 on 2024-02-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_word_correct_word_wrong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
