# Generated by Django 5.0.6 on 2024-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_user_remove_word_correct_remove_word_wrong"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="openai_key",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
