# Generated by Django 5.0.6 on 2024-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_user_openai_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="word",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
